name       : nginx
version    : 1.13.2
release    : 18
source     :
    - http://nginx.org/download/nginx-1.13.2.tar.gz : d77f234d14989d273a363f570e1d892395c006fef2ec04789be90f41a1919b70
license    : BSD-2-Clause
component  : programming
summary    : nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server.
description: |
    nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server.
builddeps  :
    - pkgconfig(gdlib)
    - pkgconfig(libpcre)
    - pkgconfig(libxslt)
    - pkgconfig(openssl)
    - libpth-devel
setup      : |
    loggingDir=/var/log/nginx/
    ./configure --prefix=/usr \
        --build=x86_64-solus-linux \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=$loggingDir/error.log \
        --group=nginx \
        --http-log-path=$loggingDir/access.log \
        --pid-path=/run/nginx.pid \
        --user=nginx \
        --with-file-aio \
        --with-http_image_filter_module \
        --with-http_ssl_module \
        --with-http_v2_module \
        --with-http_xslt_module \
        --with-pcre-jit \
        --with-threads
build      : |
    %make
install    : |
    vimDir=$installdir/usr/share/vim/vimfiles/
    install -dm00644 $installdir/etc/nginx/
    install -dm00644 $installdir/usr/share/nginx/
    install -dm00644 $vimDir
    %make_install
    # Install nginx systemd stuff
    install -Dm00644 $pkgfiles/nginx.service $installdir/%libdir%/systemd/system/nginx.service
    install -Dm00644 $pkgfiles/nginx.sysusers $installdir/%libdir%/sysusers.d/nginx.conf
    install -Dm00644 $pkgfiles/nginx.tmpfiles $installdir/%libdir%/tmpfiles.d/nginx.conf
    # Move HTML and vim stuff
    mv $installdir/usr/html $installdir/usr/share/nginx/
    mv %workdir%/contrib/vim/* $vimDir/
    # Move defaults into vendor dir for safety
    mv $installdir/etc/nginx/*.default $installdir/usr/share/nginx/
    # Move our configuration
    install -Dm00644 $pkgfiles/nginx.conf $installdir/etc/nginx/nginx.conf
    # Cleanup
    rm -rf $installdir/{run,var}
