name       : nginx
version    : 1.11.1
release    : 1
source     :
    - http://nginx.org/download/nginx-1.11.1.tar.gz : 5d8dd0197e3ffeb427729c045382182fb28db8e045c635221b2e0e6722821ad0
license    : BSD-2-Clause
component  : programming
summary    : nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server.
description: |
    nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server.
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(openssl)
setup      : |
    loggingDir=/var/log/nginx/
    ./configure --prefix=/usr \
        --build=x86_64-solus-linux \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=$loggingDir/error.log \
        --group=nginx \
        --http-log-path=$loggingDir/access.log \
        --pid-path=$loggingDir/nginx.pid \
        --user=nginx \
        --with-http_ssl_module
build      : |
    %make
install    : |
    vimDir=$installdir/usr/share/vim/vimfiles/
    install -dm00644 $installdir/etc/nginx/
    install -dm00644 $installdir/usr/share/nginx/
    install -dm00644 $vimDir
    %make_install
    # Install nginx systemd stuff
    install -Dm00644 $pkgfiles/nginx.sysusers $installdir/%libdir%/sysusers.d/nginx.conf
    install -Dm00644 $pkgfiles/nginx.tmpfiles $installdir/%libdir%/tmpfiles.d/nginx.conf
    mv %workdir%/contrib/vim/* $vimDir/
    # Move HTML stuff
    mv $installdir/usr/html $installdir/usr/share/nginx/
    # Move defaults into vendor dir for safety
    mv $installdir/etc/nginx/*.default $installdir/usr/share/nginx/
    # Move our configuration
    install -Dm00644 $pkgfiles/nginx.conf $installdir/etc/nginx/nginx.conf
    rm -rf $installdir/var
