name       : nginx
version    : 1.23.2
release    : 43
source     :
    - https://nginx.org/download/nginx-1.23.2.tar.gz : a80cc272d3d72aaee70aa8b517b4862a635c0256790434dbfc4d618a999b0b46
license    : BSD-2-Clause
component  : programming
summary    : Multi-purpose TCP server, mainly a proxy or HTTP server
description: |
    nginx is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server.
builddeps  :
    - pkgconfig(libpcre2-8)
    - pkgconfig(libxcrypt)
    - pkgconfig(libxslt)
    - libpth-devel
setup      : |
    %patch -p1 < $pkgfiles/Load-welcome-website-if-no-other-sites-are-available.patch
    %patch -p1 < $pkgfiles/Customize-welcome-page.patch
    loggingDir=/var/log/nginx
    ./configure --build=x86_64-solus-linux \
        --conf-path=/usr/share/defaults/nginx/nginx.conf \
        --error-log-path=$loggingDir/error.log \
        --group=nginx \
        --http-log-path=$loggingDir/access.log \
        --pid-path=/run/nginx.pid \
        --prefix=/usr \
        --user=nginx \
        --with-file-aio \
        --with-http_gunzip_module \
        --with-http_gzip_static_module \
        --with-http_ssl_module \
        --with-http_v2_module \
        --with-http_xslt_module \
        --with-pcre-jit \
        --with-threads
build      : |
    %make
install    : |
    %make_install

    # VIM files
    install -dm00755 $installdir/usr/share/vim/vimfiles
    cp -a $workdir/contrib/vim/* $installdir/usr/share/vim/vimfiles

    # Welcome website (appears at first run)
    install -Dm00644 $pkgfiles/welcome.conf -t $installdir/usr/share/nginx
    mv $installdir/usr/html $installdir/usr/share/nginx/welcome

    # Systemd stuff
    install -Dm00644 $pkgfiles/nginx.service -t $installdir/%libdir%/systemd/system
    install -Dm00644 $pkgfiles/nginx.sysusers $installdir/%libdir%/sysusers.d/nginx.conf
    install -Dm00644 $pkgfiles/nginx.tmpfiles $installdir/%libdir%/tmpfiles.d/nginx.conf

    # Make nginx stateless
    rm -rf $installdir/usr/share/defaults/*.default
    install -Dm00644 $pkgfiles/nginx.conf -t $installdir/usr/share/defaults/nginx

    # Cleanup
    rm -rf $installdir/{run,var}
